### PR TITLE
use safe-buffer

### PR DESCRIPTION
**Pull request by dcousens**
This way we don't explode Node<4.5.0

### CODE REVIEW

**Comment by dcousens** [comment]
needs patch release

**Comment by dcousens** [comment]
needs patch release

**Comment by fanatid** [comment]
```
$ npm owner ls hash-base
cwmma <c...f@gmail.com>
dcousens <e...l@dcousens.com>
fanatid <f...d@ya.ru>
```

:)

**Comment by dcousens** [comment]
Published as `v3.0.4`

**Pull request merged**
